import { useEffect, useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { getMyProfile, updateMyProfile } from "../../api/settings";
import { getParticipantPreferences, saveParticipantPreferences, type ParticipantPreferences } from "../../api/ecosystemRecords";
import { errorMessage } from "../../lib/errorMessage";

export default function MyProfile(){
 const[form,setForm]=useState({fullName:"",avatarUrl:"",role:""});
 const[prefs,setPrefs]=useState<ParticipantPreferences>({phone:null,preferred_contact:null,accessibility_notes:null,language:"en",network_visibility:"workspace"});
 const[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{Promise.all([getMyProfile(),getParticipantPreferences()]).then(([p,x])=>{setForm({fullName:p.full_name||"",avatarUrl:p.avatar_url||"",role:p.role});setPrefs(x)}).catch(r=>setError(errorMessage(r,"Unable to load your profile."))).finally(()=>setLoading(false))},[]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");try{const[p,x]=await Promise.all([updateMyProfile(form),saveParticipantPreferences(prefs)]);setForm(c=>({...c,fullName:p.full_name||"",avatarUrl:p.avatar_url||""}));setPrefs(x);setMessage("Profile and preferences saved.")}catch(r){setError(errorMessage(r,"Unable to save your profile."))}finally{setBusy(false)}}
 if(loading)return <main style={pageStyle}><p role="status">Loading profile…</p></main>;
 return <main style={pageStyle}><header style={heroStyle}><p style={eyebrowStyle}>One HLC identity</p><h1 style={{margin:0}}>My profile</h1><p>Your authenticated identity, contact preferences and visibility settings are reused across authorized HLC surfaces. Workspace role remains server-controlled.</p></header>{error&&<p role="alert" style={errorStyle}>{error}</p>}{message&&<p role="status" style={successStyle}>{message}</p>}<form onSubmit={submit} style={cardStyle}><h2>Identity</h2><label>Full name<input autoComplete="name" value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></label><label>Avatar URL<input type="url" value={form.avatarUrl} onChange={e=>setForm({...form,avatarUrl:e.target.value})}/></label><p><strong>Current workspace role:</strong> {form.role}</p><h2>Contact & access preferences</h2><label>Phone<input type="tel" value={prefs.phone||""} onChange={e=>setPrefs({...prefs,phone:e.target.value||null})}/></label><label>Preferred contact<select value={prefs.preferred_contact||""} onChange={e=>setPrefs({...prefs,preferred_contact:e.target.value||null})}><option value="">No preference</option><option value="email">Email</option><option value="phone">Phone</option><option value="sms">SMS</option></select></label><label>Language<input value={prefs.language} onChange={e=>setPrefs({...prefs,language:e.target.value})}/></label><label>Network visibility<select value={prefs.network_visibility} onChange={e=>setPrefs({...prefs,network_visibility:e.target.value})}><option value="private">Private</option><option value="workspace">Workspace</option><option value="network">HLC network</option></select></label><label>Accessibility notes<textarea rows={4} value={prefs.accessibility_notes||""} onChange={e=>setPrefs({...prefs,accessibility_notes:e.target.value||null})}/></label><button disabled={busy}>{busy?"Saving…":"Save profile"}</button></form><section style={cardStyle}><h2>Profile boundaries</h2><p>Visibility affects HLC product presentation only; it never overrides workspace membership, portal links, RLS, or other authorization controls.</p><div style={linksStyle}><Link to="/profiles">Participant directory</Link><Link to="/settings">Workspace settings</Link><Link to="/rules">Privacy and safety rules</Link></div></section></main>
}
const pageStyle={width:"min(820px,calc(100% - 32px))",margin:"40px auto",display:"grid",gap:18};const heroStyle={padding:"clamp(22px,5vw,40px)",borderRadius:20,color:"#f8fafc",background:"linear-gradient(135deg,#081426,#12365f)"};const eyebrowStyle={margin:0,color:"#60a5fa",fontWeight:900,textTransform:"uppercase" as const};const cardStyle={display:"grid",gap:12,padding:20,border:"1px solid #cbd5e1",borderRadius:16,background:"#fff"};const linksStyle={display:"flex",flexWrap:"wrap" as const,gap:12};const errorStyle={color:"#b91c1c"};const successStyle={color:"#166534"};
