import { useCallback, useEffect, useState } from "react";
import { createPartnerSourceByEmail, listPartnerManagementQueue, setPartnerReferralStatus, type PartnerManagementQueue } from "../../api/partnerManagement";
import { errorMessage } from "../../lib/errorMessage";

export default function PartnerManagement(){
  const[data,setData]=useState<PartnerManagementQueue>({sources:[],referrals:[]});const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");
  const[displayName,setDisplayName]=useState("");const[organizationName,setOrganizationName]=useState("");const[accountEmail,setAccountEmail]=useState("");
  const load=useCallback(async()=>{setError("");try{setData(await listPartnerManagementQueue());}catch(reason){setError(errorMessage(reason,"Unable to load partner management."));}finally{setLoading(false);}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>{void load();},0);return()=>window.clearTimeout(timer);},[load]);
  async function create(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");setMessage("");try{await createPartnerSourceByEmail({displayName,organizationName,accountEmail});setDisplayName("");setOrganizationName("");setAccountEmail("");await load();setMessage("Partner account linked and activated.");}catch(reason){setError(errorMessage(reason,"Unable to link partner access."));}finally{setBusy(false);}}
  async function setStatus(id:string,status:"recorded"|"reviewing"|"qualified"|"converted"|"closed"|"declined"){setBusy(true);setError("");try{await setPartnerReferralStatus(id,status);await load();setMessage(`Referral marked ${status}.`);}catch(reason){setError(errorMessage(reason,"Unable to update referral status."));}finally{setBusy(false);}}
  return <main className="hlc-portal-workspace is-professional"><header className="hlc-portal-header"><div><p className="hlc-account-kicker">PARTNER OPERATIONS</p><h1>Partner sources & referrals</h1><p>Approve a registered account as a partner source and move attributed referrals through explicit status states.</p></div><div className="hlc-portal-summary"><span><strong>{data.sources.length}</strong><small>Partner sources</small></span><span><strong>{data.referrals.length}</strong><small>Referrals</small></span></div></header>
    {loading&&<p className="hlc-portal-state">Loading partner operations…</p>}{error&&<p role="alert" className="hlc-account-status is-error">{error}</p>}{message&&<p role="status" className="hlc-account-status is-success">{message}</p>}
    <section className="hlc-portal-project"><h2>Activate partner access</h2><form onSubmit={create}><label>Partner display name<input required value={displayName} onChange={e=>setDisplayName(e.target.value)}/></label><label>Organization<input value={organizationName} onChange={e=>setOrganizationName(e.target.value)}/></label><label>Registered account email<input required type="email" value={accountEmail} onChange={e=>setAccountEmail(e.target.value)}/></label><p>The person must already have a registered HLC account. This links only partner access; it does not grant workspace membership.</p><button disabled={busy}>Activate partner</button></form></section>
    <section className="hlc-portal-project"><h2>Partner sources</h2>{!data.sources.length?<p>No partner sources yet.</p>:data.sources.map(source=><article className="hlc-portal-row" key={source.id}><strong>{source.organization_name||source.display_name}</strong><span>{source.status}</span><p>{source.contact_email||"No contact email recorded"}</p></article>)}</section>
    <section className="hlc-portal-project"><h2>Referral queue</h2>{!data.referrals.length?<p>No partner referrals yet.</p>:data.referrals.map(referral=><article className="hlc-portal-row" key={referral.id}><div><strong>{referral.referred_name||referral.referred_email||referral.referred_phone||"Referral"}</strong><span>{referral.partner_name} · {referral.target_kind} · {referral.status}</span>{referral.note&&<p>{referral.note}</p>}</div><div className="hlc-portal-actions">{(["reviewing","qualified","converted","closed","declined"] as const).map(status=><button type="button" disabled={busy||referral.status===status} key={status} onClick={()=>void setStatus(referral.id,status)}>{status}</button>)}</div></article>)}</section>
  </main>;
}
