import { useEffect, useState, type FormEvent } from "react";
import { getBusinessProfile, getMyProfile, listMyWorkspaces, saveBusinessProfile, switchCurrentWorkspace, updateMyProfile, type WorkspaceOption } from "../../api/settings";
import { errorMessage } from "../../lib/errorMessage";
import { getBillingOffer, getBillingStatus, openBillingPortal, startSubscriptionCheckout, type BillingOffer, type BillingStatus } from "../../api/billing";
import { listBusinessPhones, type BusinessPhone } from "../../api/telephony";
import { Link } from "react-router-dom";
import { DeviceAlertSettings } from "../../components/notifications/RealtimeNotificationCenter";
import IntegrationsConnectionsPanel from "../../components/settings/IntegrationsConnectionsPanel";

const blankBusiness = { business_name: "", owner_name: "", phone: "", email: "", website: "", address: "", city: "", state: "", zip: "" };
function formatBillingOffer(offer: BillingOffer) { const amount = new Intl.NumberFormat("en-US", { style: "currency", currency: offer.currency.toUpperCase() }).format(offer.price_cents / 100); return `${amount} per ${offer.interval}`; }

export default function Settings() {
  const billingEnabled = import.meta.env.VITE_BILLING_ENABLED === "true";
  const [personal, setPersonal] = useState({ fullName: "", avatarUrl: "", role: "" });
  const [business, setBusiness] = useState(blankBusiness);
  const [workspaces, setWorkspaces] = useState<WorkspaceOption[]>([]); const [workspaceId, setWorkspaceId] = useState("");
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState<"personal" | "business" | null>(null); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const [billing, setBilling] = useState<BillingStatus | null>(null); const [billingOffer, setBillingOffer] = useState<BillingOffer | null>(null); const [billingSetupError, setBillingSetupError] = useState(""); const [billingConsent, setBillingConsent] = useState(false);
  const [businessPhones, setBusinessPhones] = useState<BusinessPhone[]>([]); const [phoneSetupError, setPhoneSetupError] = useState("");

  useEffect(() => { let active = true; async function loadSettings() { try {
    const [profile, businessProfile, workspaceOptions] = await Promise.all([getMyProfile(), getBusinessProfile(), listMyWorkspaces()]); if (!active) return;
    setWorkspaceId(profile.workspace_id); setWorkspaces(workspaceOptions); setPersonal({ fullName: profile.full_name || "", avatarUrl: profile.avatar_url || "", role: profile.role });
    if (businessProfile) setBusiness({ business_name: businessProfile.business_name || "", owner_name: businessProfile.owner_name || "", phone: businessProfile.phone || "", email: businessProfile.email || "", website: businessProfile.website || "", address: businessProfile.address || "", city: businessProfile.city || "", state: businessProfile.state || "", zip: businessProfile.zip || "" });
    const phoneResult = await Promise.allSettled([listBusinessPhones()]); if (!active) return; if (phoneResult[0].status === "fulfilled") { setBusinessPhones(phoneResult[0].value); setPhoneSetupError(""); } else { setBusinessPhones([]); setPhoneSetupError(errorMessage(phoneResult[0].reason, "Unable to verify phone provider status.")); }
    if (billingEnabled) { const [statusResult, offerResult] = await Promise.allSettled([getBillingStatus(), getBillingOffer()]); if (!active) return; if (statusResult.status === "fulfilled") setBilling(statusResult.value); else setBillingSetupError(errorMessage(statusResult.reason, "Unable to verify workspace billing status.")); if (offerResult.status === "fulfilled") setBillingOffer(offerResult.value); else setBillingSetupError(current => current || errorMessage(offerResult.reason, "Unable to verify the HLC billing offer.")); }
  } catch (reason) { if (active) setError(errorMessage(reason, "Unable to load settings.")); } finally { if (active) setLoading(false); } } void loadSettings(); return () => { active = false; }; }, [billingEnabled]);

  async function run(kind: "personal" | "business", action: () => Promise<void>, success: string) { setBusy(kind); setError(""); setMessage(""); try { await action(); setMessage(success); } catch (reason) { setError(errorMessage(reason, "Unable to save settings.")); } finally { setBusy(null); } }
  async function savePersonal(event: FormEvent) { event.preventDefault(); await run("personal", async () => { const updated = await updateMyProfile(personal); setPersonal(current => ({ ...current, fullName: updated.full_name || "", avatarUrl: updated.avatar_url || "" })); }, "Personal profile saved."); }
  async function changeWorkspace(event: FormEvent) { event.preventDefault(); await run("personal", async () => { await switchCurrentWorkspace(workspaceId); window.location.assign("/dashboard"); }, "Workspace switched."); }
  async function saveBusiness(event: FormEvent) { event.preventDefault(); await run("business", async () => { const updated = await saveBusinessProfile(business); setBusiness({ business_name: updated.business_name || "", owner_name: updated.owner_name || "", phone: updated.phone || "", email: updated.email || "", website: updated.website || "", address: updated.address || "", city: updated.city || "", state: updated.state || "", zip: updated.zip || "" }); }, "Business profile saved."); }
  async function billingAction(action: () => Promise<void>) { setError(""); setMessage(""); try { await action(); } catch (reason) { setError(errorMessage(reason, "Billing is currently unavailable.")); } }

  if (loading) return <main className="hlc-account-workspace"><p role="status">Loading settings…</p></main>;
  const billingOfferLabel = billingOffer ? formatBillingOffer(billingOffer) : null; const billingReady = billingEnabled && billingOfferLabel && !billingSetupError;
  return <main className="hlc-account-workspace">
    <header className="hlc-account-header"><div><p className="hlc-account-kicker">ACCOUNT CONTROL</p><h1>Profile, business & connections</h1><p>Manage the identity, workspace, business, integrations, telephony, alerts, and billing controls supported by your HLC workspace.</p></div><div className="hlc-account-summary"><span><strong>{workspaces.length}</strong><small>Available workspaces</small></span><span><strong>{businessPhones.length}</strong><small>Business lines</small></span><span><strong>{personal.role}</strong><small>Server role</small></span></div></header>
    {error && <p role="alert" className="hlc-account-status is-error">{error}</p>}{message && <p role="status" className="hlc-account-status is-success">{message}</p>}
    <div className="hlc-settings-ledger">
      <form onSubmit={changeWorkspace} className="hlc-settings-section"><div className="hlc-account-section-head"><div><span>WORKSPACE</span><h2>Current workspace</h2></div><small>Membership-backed</small></div><label>Workspace<select value={workspaceId} onChange={event => setWorkspaceId(event.target.value)}>{workspaces.map(workspace => <option key={workspace.id} value={workspace.id}>{workspace.name}</option>)}</select></label><div className="hlc-account-form-actions"><span>Only linked memberships are listed.</span><button disabled={busy !== null || !workspaceId} type="submit">Switch workspace</button></div></form>
      <form onSubmit={savePersonal} className="hlc-settings-section"><div className="hlc-account-section-head"><div><span>PERSONAL</span><h2>Personal profile</h2></div><strong>{personal.role}</strong></div><div className="hlc-account-field-grid"><label>Full name<input value={personal.fullName} onChange={event => setPersonal({ ...personal, fullName: event.target.value })} /></label><label>Avatar URL<input type="url" value={personal.avatarUrl} onChange={event => setPersonal({ ...personal, avatarUrl: event.target.value })} /></label></div><div className="hlc-account-form-actions"><span>Workspace role remains server-controlled.</span><button disabled={busy !== null} type="submit">{busy === "personal" ? "Saving…" : "Save personal profile"}</button></div></form>
      <form onSubmit={saveBusiness} className="hlc-settings-section"><div className="hlc-account-section-head"><div><span>BUSINESS</span><h2>Business profile</h2></div></div><div className="hlc-account-field-grid">{Object.entries({ business_name: "Business name", owner_name: "Owner name", phone: "Phone", email: "Email", website: "Website", address: "Street address", city: "City", state: "State", zip: "ZIP" }).map(([field, label]) => <label key={field}>{label}<input type={field === "email" ? "email" : field === "website" ? "url" : field === "phone" ? "tel" : "text"} value={business[field as keyof typeof business]} onChange={event => setBusiness({ ...business, [field]: event.target.value })} /></label>)}</div><div className="hlc-account-form-actions"><span>Canonical workspace business identity.</span><button disabled={busy !== null} type="submit">{busy === "business" ? "Saving…" : "Save business profile"}</button></div></form>
      <IntegrationsConnectionsPanel businessPhones={businessPhones} phoneError={phoneSetupError} billingEnabled={billingEnabled} billing={billing} billingError={billingSetupError} />
      <section className="hlc-settings-section" aria-labelledby="phone-settings-heading"><div className="hlc-account-section-head"><div><span>TELEPHONY</span><h2 id="phone-settings-heading">Business phone numbers</h2></div><strong>{businessPhones.length}</strong></div><p>Provider readiness determines which calling and messaging actions are available.</p>{phoneSetupError ? <p role="alert" className="hlc-account-status is-error">{phoneSetupError}</p> : businessPhones.length === 0 ? <p className="hlc-account-state"><strong>Phone provider setup required.</strong></p> : <div className="hlc-phone-list">{businessPhones.map(phone => <article className="hlc-phone-row" key={phone.id}><div><strong>{phone.display_name}: {phone.phone_number}</strong><span>{phone.provider_type} · {phone.readiness_state} · {phone.verification_state}{phone.is_primary ? " · Primary" : ""}</span></div><small>{phone.inbound_enabled ? "Inbound enabled" : "Inbound unavailable"} · {phone.outbound_enabled ? "Outbound enabled" : "Outbound unavailable"} · {phone.sms_enabled ? "SMS enabled" : "SMS unavailable"} · {phone.browser_calling_enabled ? "Browser calling enabled" : "Browser calling unavailable"}</small></article>)}</div>}<nav className="hlc-account-inline-links"><Link to="/manual-communications">Open communications logging</Link><Link to="/call-center">Open call center</Link></nav><small>Provider credentials stay in the trusted server environment, never in workspace settings.</small></section>
      <section className="hlc-settings-section"><div className="hlc-account-section-head"><div><span>DEVICE</span><h2>Alerts</h2></div></div><DeviceAlertSettings /></section>
      <section className="hlc-settings-section"><div className="hlc-account-section-head"><div><span>BILLING</span><h2>Subscription</h2></div><strong>{billing?.status || (billingEnabled ? "unverified" : "disabled")}</strong></div>{billingSetupError && <p role="alert" className="hlc-account-status is-error">{billingSetupError}</p>}{billingReady ? <><p><strong>{billingOffer?.name}:</strong> {billingOfferLabel} after a 14-day free trial.</p><p>A payment method is required to begin the trial. No charge is made until the trial ends. Cancellation of a paid subscription takes effect at the end of the current billing period.</p></> : billingEnabled && !billingSetupError ? <p><strong>Setup required:</strong> The authoritative HLC billing offer is unavailable, so enrollment is disabled.</p> : null}{!billing?.is_active && billingReady && <label className="hlc-billing-consent"><input type="checkbox" checked={billingConsent} onChange={event => setBillingConsent(event.target.checked)} /> <span>I agree to begin a 14-day free trial with a payment method. Unless cancelled before the trial ends, the workspace will be charged {billingOfferLabel}. I can cancel online through the Stripe billing portal.</span></label>}{billing ? <p>Workspace billing state: <strong>{billing.status}</strong>{billing.trial_end ? ` · Trial ends ${new Date(billing.trial_end).toLocaleDateString()}` : ""}{billing.current_period_end ? ` · Current period ends ${new Date(billing.current_period_end).toLocaleDateString()}` : ""}</p> : billingEnabled && !billingSetupError ? <p>No authoritative Stripe subscription is recorded for this workspace.</p> : null}{billingEnabled ? <div className="hlc-account-inline-links">{!billing?.is_active && <button disabled={!billingConsent || !billingReady} type="button" onClick={() => billingAction(startSubscriptionCheckout)}>Start 14-day trial</button>}{billing && <button type="button" onClick={() => billingAction(openBillingPortal)}>Manage billing with Stripe</button>}</div> : <p><strong>Setup required:</strong> Stripe launch billing is not enabled in this environment.</p>}</section>
    </div>
  </main>;
}
