import MobileNavigationDialogAccessibility from "../components/accessibility/MobileNavigationDialogAccessibility";
import "./authenticated-entry";
import "./desktop-agent-team-rail.css";
import "./desktop-data-workspaces.css";
import "./desktop-page-archetypes.css";
import "./desktop-core-workspaces.css";
import "./desktop-workflow-communications.css";
import "./desktop-discovery-community.css";
import "./desktop-account-portals-agents.css";
import "./calendar-mobile-action-order.css";
import "./launch-messaging-simplification.css";
import "./five-star-mobile-routes.css";
import "./five-star-mobile-secondary.css";
import "./five-star-mobile-admin.css";
import "./five-star-mobile-more.css";
import "./five-star-mobile-physical-qa.css";
import "./five-star-mobile-physical-resources.css";
import "./mobile-a-plus-sprint-2-work.css";
import "./mobile-a-plus-sprint-2-iphone-qa.css";
import "./mobile-a-plus-sprint-2-shell-closure.css";
import "./mobile-a-plus-sprint-3-network.css";
import "./mobile-a-plus-sprint-4-community-messages.css";
import "./mobile-a-plus-sprint-5-community-participation.css";
import "./mobile-a-plus-sprint-6-account-portals-resources.css";
import "./mobile-a-plus-sprint-7-integrated-accessibility.css";
import "./mobile-a-plus-final-device-corrections.css";
import "./mobile-a-plus-final-device-round-2.css";
import "./provider-professional-profile.css";
import "./mobile-a-plus-final-device-round-3.css";
import "./mobile-a-plus-private-beta-closure.css";
import "./e5-intelligence-sandbox.css";
import "./e6-trial-entitlements.css";
import "./hlc-unified-settings-index.css";
import "./hlc-unified-screen-archetypes.css";
import "./hlc-unified-detail-workspaces.css";
import "./hlc-dashboard-structural-correction.css";
import "./hlc-structural-correction.css";
import "./hlc-purpose-built-workspaces.css";
import "./hlc-desktop-mobile-nav-guard.css";
import "./universal-ai-team-launcher.css";
import "./jobs-dashboard-a.css";
import "./calendar-dashboard-a.css";
import "./follow-ups-dashboard-a.css";
import "./workflow-dashboard-a.css";
import "./automations-dashboard-a.css";
import "./mobile-command-menu-rebuild-20260905.css";
import "./dashboard-context-hero.css";

export default function AuthenticatedStyles() {
  return <MobileNavigationDialogAccessibility />;
}
