import { useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import {
  decideContractorAssignment, getContractorPortalData, getContractorPortalProgress, getLinkedProviderPerformance,
  getLinkedProviderVerification, recordContractorJobProgress,
  type ContractorPortalData, type LinkedProviderVerification, type ProviderPerformance, type ProviderProgress,
} from "../../api/portals";
import { errorMessage } from "../../lib/errorMessage";
import { getDocumentUrl, listDocuments, type DocumentRecord } from "../../api/documents";

type ProfessionalNextStep={title:string;detail:string;route?:string;action?:string};
function resolveProfessionalNextStep(data:ContractorPortalData,verification:LinkedProviderVerification|null):ProfessionalNextStep{
  if(!data.links.length)return{title:"Connect your professional profile",detail:"Start with the professional application or use an approved portal invitation. An email match alone never grants provider access.",route:"/professional-application",action:"Open professional application"};
  if(verification&&verification.status!=="verified")return{title:"Complete provider verification",detail:`Current verification state: ${verification.status}. HLC management owns approval; this portal cannot self-verify. Keep profile, services, service area, and availability accurate while review is pending.`,route:"/contractor-portal/profile",action:"Review business profile"};
  if(data.assignments.some(a=>a.status==="offered"))return{title:"Review your work offer",detail:"A real assignment is waiting for your accept or reject decision below."};
  if(data.assignments.some(a=>a.status==="accepted"&&a.appointments.some(appt=>appt.status==="scheduled")))return{title:"Prepare for scheduled work",detail:"An accepted assignment now has a scheduled visit. Review the appointment, customer details, Messages, and shared evidence before service.",route:"/messages",action:"Open messages"};
  if(data.assignments.some(a=>a.status==="accepted"))return{title:"Update active work",detail:"Accepted work can now record provider-owned progress without silently rewriting HLC's canonical job status."};
  return{title:"Keep your work profile ready",detail:"No offer currently needs action. Confirm services, service area, and availability so HLC has current provider-declared facts.",route:"/contractor-portal/services",action:"Review services & availability"};
}

export default function ContractorPortal(){
  const[data,setData]=useState<ContractorPortalData>({links:[],assignments:[]});const[verification,setVerification]=useState<LinkedProviderVerification|null>(null);const[progress,setProgress]=useState<ProviderProgress[]>([]);const[performance,setPerformance]=useState<ProviderPerformance|null>(null);const[documents,setDocuments]=useState<DocumentRecord[]>([]);
  const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");const[notes,setNotes]=useState<Record<string,string>>({});
  const load=useCallback(async()=>{setError("");try{const portal=await getContractorPortalData();setData(portal);const contractorId=portal.links[0]?.contractor_id;const extras=contractorId?await Promise.all([getLinkedProviderVerification(contractorId),getContractorPortalProgress(),getLinkedProviderPerformance(contractorId),listDocuments()]):[null,[],null,await listDocuments()] as const;setVerification(extras[0] as LinkedProviderVerification|null);setProgress(extras[1] as ProviderProgress[]);setPerformance(extras[2] as ProviderPerformance|null);setDocuments(extras[3] as DocumentRecord[]);}catch(reason){setError(errorMessage(reason,"Unable to load professional work."));}finally{setLoading(false);}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>{void load();},0);return()=>window.clearTimeout(timer);},[load]);
  async function act(action:()=>Promise<unknown>,success:string){setBusy(true);setError("");setMessage("");try{await action();await load();setMessage(success);}catch(reason){setError(errorMessage(reason,"Unable to complete that action."));}finally{setBusy(false);}}
  async function openDocument(document:DocumentRecord){try{window.open(await getDocumentUrl(document.id,document.storage_path),"_blank","noopener,noreferrer");}catch(reason){setError(errorMessage(reason,"Unable to open this document."));}}
  const offered=data.assignments.filter(a=>a.status==="offered").length;const nextStep=useMemo(()=>resolveProfessionalNextStep(data,verification),[data,verification]);
  return <main className="hlc-portal-workspace is-professional">
    <header className="hlc-portal-header"><div><p className="hlc-account-kicker">PROFESSIONAL PORTAL</p><h1>Assignment workspace</h1><p>Verification, offers, assigned work, provider-reported progress, and performance for companies explicitly linked to your authenticated portal relationship.</p></div><div className="hlc-portal-summary"><span><strong>{data.assignments.length}</strong><small>Assignments</small></span><span><strong>{offered}</strong><small>Offers awaiting decision</small></span><span><strong>{performance?.completed_jobs??0}</strong><small>Completed jobs</small></span></div></header>
    <nav aria-label="Professional portal sections" className="hlc-portal-actions"><Link to="/contractor-portal">Work dashboard</Link><Link to="/contractor-portal/profile">Business profile</Link><Link to="/contractor-portal/services">Services & availability</Link><Link to="/messages">Messages</Link><Link to="/contractor-portal/documents">Documents</Link></nav>
    {!loading&&!error&&<section className="hlc-portal-project"><div className="hlc-account-section-head"><div><span>WHAT'S NEXT</span><h2>{nextStep.title}</h2></div></div><p>{nextStep.detail}</p>{nextStep.route&&<div className="hlc-portal-actions"><Link to={nextStep.route}>{nextStep.action}</Link></div>}</section>}
    {loading&&<p className="hlc-portal-state">Loading contractor work…</p>}{error&&<p role="alert" className="hlc-account-status is-error">{error}</p>}{message&&<p role="status" className="hlc-account-status is-success">{message}</p>}
    {data.links.length>0&&<section className="hlc-portal-project"><div className="hlc-account-section-head"><div><span>READINESS</span><h2>Verification</h2></div><strong>{verification?.status??"unknown"}</strong></div><p>{verification?.note||"No management verification note is recorded."}</p>{verification?.verified_at&&<p>Verified {new Date(verification.verified_at).toLocaleString()}</p>}<p>This status is management-owned. Professional accounts cannot approve themselves.</p></section>}
    <section className="hlc-portal-project"><div className="hlc-account-section-head"><div><span>WORK QUEUE</span><h2>Offers & assigned jobs</h2></div><strong>{data.assignments.length}</strong></div>{!data.assignments.length&&data.links.length>0&&<p className="hlc-portal-state">No job offers or assigned work. Keep services and availability current while you wait.</p>}{data.assignments.map(assignment=><article className="hlc-portal-row" key={assignment.id}><div><strong>{assignment.job.name}</strong><span>Assignment {assignment.status} · Job {assignment.job.status}</span>{assignment.job.customer&&<p>Customer: {assignment.job.customer.name||"Not specified"} · {[assignment.job.customer.phone,assignment.job.customer.email].filter(Boolean).join(" · ")}</p>}<h3>Appointments</h3>{!assignment.appointments.length?<p>No appointments.</p>:<ul>{assignment.appointments.map(appt=><li key={appt.id}>{new Date(appt.appointment_date).toLocaleString()} – {appt.appointment_end_at?new Date(appt.appointment_end_at).toLocaleString():"End time unavailable"} · {appt.status}</li>)}</ul>}<div className="hlc-portal-actions"><Link to="/messages">Message about work</Link><Link to="/contractor-portal/documents">Open documents</Link></div></div>{assignment.status==="offered"&&<div className="hlc-portal-actions"><button disabled={busy} onClick={()=>void act(()=>decideContractorAssignment(assignment.id,"accepted"),"Offer accepted.")}>Accept offer</button><button disabled={busy} onClick={()=>void act(()=>decideContractorAssignment(assignment.id,"rejected"),"Offer rejected.")}>Reject offer</button></div>}{assignment.status==="accepted"&&<div><label>Progress note<textarea value={notes[assignment.id]??""} onChange={e=>setNotes(current=>({...current,[assignment.id]:e.target.value}))}/></label><div className="hlc-portal-actions">{(["started","in_progress","blocked","completed"] as ProviderProgress["status"][]).map(status=><button key={status} disabled={busy} onClick={()=>void act(()=>recordContractorJobProgress(assignment.id,status,notes[assignment.id]??""),`Progress recorded: ${status.replaceAll("_"," ")}.`)}>{status.replaceAll("_"," ")}</button>)}</div><p>Provider progress is evidence only. HLC operations retains authority over the canonical job lifecycle.</p></div>}</article>)}</section>
    <section className="hlc-portal-project"><div className="hlc-account-section-head"><div><span>PROGRESS HISTORY</span><h2>Your reported updates</h2></div><strong>{progress.length}</strong></div>{!progress.length?<p>No provider progress reports yet.</p>:progress.map(item=><article className="hlc-portal-row" key={item.id}><strong>{item.status.replaceAll("_"," ")}</strong><span>{new Date(item.created_at).toLocaleString()}</span>{item.note&&<p>{item.note}</p>}</article>)}</section>
    <section className="hlc-portal-project"><div className="hlc-account-section-head"><div><span>PERFORMANCE</span><h2>Recorded service history</h2></div></div>{performance?<dl><div><dt>Accepted assignments</dt><dd>{performance.accepted_assignments}</dd></div><div><dt>Completed HLC jobs</dt><dd>{performance.completed_jobs}</dd></div><div><dt>Provider completion reports</dt><dd>{performance.provider_completed_reports}</dd></div><div><dt>Published reviews</dt><dd>{performance.published_reviews}</dd></div><div><dt>Average rating</dt><dd>{performance.average_rating??"No rating yet"}</dd></div></dl>:<p>No performance record is available yet.</p>}</section>
    <section className="hlc-portal-project"><div className="hlc-account-section-head"><div><span>SHARED EVIDENCE</span><h2>Documents</h2></div><strong>{documents.length}</strong></div>{!documents.length?<p className="hlc-portal-state">No documents have been shared with your professional account.</p>:documents.map(document=><article className="hlc-portal-file-row" key={document.id}><button type="button" onClick={()=>void openDocument(document)}>{document.filename}</button><span>{document.entity_type}</span></article>)}</section>
  </main>;
}
