import { useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import {
  createHomeownerReferral, createHomeownerReview, decideHomeownerEstimate, decideHomeownerProviderMatch,
  getHomeownerPortalData, getHomeownerPortalMatches, getHomeownerPortalPayments,
  listHomeownerReferrals, listHomeownerReviewEligibleJobs, listHomeownerReviews,
  type HomeownerPortalRelationship, type ResidentJobPayment, type ResidentProviderMatch, type ResidentReferral,
  type ResidentReview, type ResidentReviewEligibleJob,
} from "../../api/portals";
import { errorMessage } from "../../lib/errorMessage";
import { formatCurrency } from "../../lib/estimator/calculations";
import { getDocumentUrl, listDocuments, type DocumentRecord } from "../../api/documents";

type ResidentNextStep={title:string;detail:string;route:string;action:string};
function resolveResidentNextStep(relationships:HomeownerPortalRelationship[],matches:ResidentProviderMatch[],payments:ResidentJobPayment[],eligibleReviews:ResidentReviewEligibleJob[]):ResidentNextStep{
  if(!relationships.length)return{title:"Start with your service request",detail:"Tell HLC what you need help with. Once your request is linked to this account, its progress will appear here.",route:"/request-service",action:"Request service"};
  if(relationships.flatMap(x=>x.estimates).some(x=>x.status==="sent"))return{title:"Review your estimate",detail:"An estimate is waiting for your deliberate decision.",route:"/homeowner-portal/requests",action:"Open requests"};
  if(matches.some(x=>x.status==="proposed"))return{title:"Review your provider match",detail:"HLC has proposed a provider. Review the recorded provider facts and accept or decline the match below.",route:"#resident-matches",action:"Review provider"};
  const due=payments.find(x=>["pending","checkout_created","processing","failed"].includes(x.status));
  if(due)return{title:"Payment needs attention",detail:due.status==="failed"?"The last payment attempt failed. Use the available checkout action when HLC has issued a new secure session.":"A job payment record is active. Use only the secure checkout shown below.",route:"#resident-payments",action:"Open payment"};
  if(eligibleReviews.length)return{title:"Share your completed-service review",detail:"A completed linked job is eligible for one review.",route:"#resident-reviews",action:"Write review"};
  const jobs=relationships.flatMap(x=>x.jobs);const scheduled=jobs.find(j=>j.appointments.some(a=>a.status==="scheduled"));
  if(scheduled)return{title:"Your visit is scheduled",detail:"Open Appointments for the confirmed date and time.",route:"/homeowner-portal/appointments",action:"Open appointments"};
  const active=jobs.find(j=>!["completed","cancelled"].includes(j.status));if(active)return{title:"Track your active service",detail:"Your project is active. Jobs, Messages, and shared evidence remain your source of truth.",route:"/homeowner-portal/jobs",action:"Open jobs"};
  const completed=jobs.find(j=>j.status==="completed");if(completed)return{title:"Service is recorded complete",detail:"Review the completed work, payment state, and any eligible review/referral actions below.",route:"/homeowner-portal/jobs",action:"Review completed work"};
  return{title:"Your request is being worked",detail:"HLC has your request. Open Requests for its current stage or Messages if you need to add information.",route:"/homeowner-portal/requests",action:"Open requests"};
}

export default function HomeownerPortal(){
  const[relationships,setRelationships]=useState<HomeownerPortalRelationship[]>([]);const[matches,setMatches]=useState<ResidentProviderMatch[]>([]);const[payments,setPayments]=useState<ResidentJobPayment[]>([]);const[eligibleReviews,setEligibleReviews]=useState<ResidentReviewEligibleJob[]>([]);const[reviews,setReviews]=useState<ResidentReview[]>([]);const[referrals,setReferrals]=useState<ResidentReferral[]>([]);const[documents,setDocuments]=useState<DocumentRecord[]>([]);
  const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");
  const[reviewJobId,setReviewJobId]=useState("");const[rating,setRating]=useState(5);const[reviewBody,setReviewBody]=useState("");const[referralEmail,setReferralEmail]=useState("");const[referralNote,setReferralNote]=useState("");
  const load=useCallback(async()=>{setError("");try{const[r,m,p,e,rv,rf,d]=await Promise.all([getHomeownerPortalData(),getHomeownerPortalMatches(),getHomeownerPortalPayments(),listHomeownerReviewEligibleJobs(),listHomeownerReviews(),listHomeownerReferrals(),listDocuments()]);setRelationships(r);setMatches(m);setPayments(p);setEligibleReviews(e);setReviews(rv);setReferrals(rf);setDocuments(d);if(!reviewJobId&&e[0])setReviewJobId(e[0].id);}catch(reason){setError(errorMessage(reason,"Unable to load your service workspace."));}finally{setLoading(false);}},[reviewJobId]);
  useEffect(()=>{void load();},[load]);
  const estimates=useMemo(()=>relationships.reduce((sum,item)=>sum+item.estimates.length,0),[relationships]);const jobs=useMemo(()=>relationships.reduce((sum,item)=>sum+item.jobs.length,0),[relationships]);const nextStep=useMemo(()=>resolveResidentNextStep(relationships,matches,payments,eligibleReviews),[relationships,matches,payments,eligibleReviews]);
  async function act(action:()=>Promise<unknown>,success:string){setBusy(true);setError("");setMessage("");try{await action();await load();setMessage(success);}catch(reason){setError(errorMessage(reason,"Unable to complete that action."));}finally{setBusy(false);}}
  async function openDocument(document:DocumentRecord){try{window.open(await getDocumentUrl(document.id,document.storage_path),"_blank","noopener,noreferrer");}catch(reason){setError(errorMessage(reason,"Unable to open this document."));}}
  const referralLeadId=relationships[0]?.lead_id;
  return <main className="hlc-portal-workspace is-resident">
    <header className="hlc-portal-header"><div><p className="hlc-account-kicker">RESIDENT PORTAL</p><h1>Your service workspace</h1><p>Move from request to provider, service, payment, review, and repeat help without entering internal HLC workspaces.</p></div><div className="hlc-portal-summary"><span><strong>{estimates}</strong><small>Estimates</small></span><span><strong>{jobs}</strong><small>Jobs</small></span><span><strong>{documents.length}</strong><small>Shared files</small></span></div></header>
    <nav aria-label="Resident service actions" className="hlc-portal-actions"><Link to="/request-service">New request</Link><Link to="/homeowner-portal/requests">Requests</Link><Link to="/homeowner-portal/appointments">Appointments</Link><Link to="/homeowner-portal/jobs">Jobs</Link><Link to="/messages">Messages</Link><Link to="/homeowner-portal/documents">Documents</Link></nav>
    {!loading&&!error&&<section className="hlc-portal-project"><div className="hlc-account-section-head"><div><span>WHAT'S NEXT</span><h2>{nextStep.title}</h2></div></div><p>{nextStep.detail}</p><div className="hlc-portal-actions"><a href={nextStep.route}>{nextStep.action}</a></div></section>}
    {loading&&<p className="hlc-portal-state">Loading your projects…</p>}{error&&<p role="alert" className="hlc-account-status is-error">{error}</p>}{message&&<p role="status" className="hlc-account-status is-success">{message}</p>}
    {!loading&&!error&&!relationships.length&&<p className="hlc-portal-state">No projects are linked to this account yet.</p>}
    <div className="hlc-portal-ledger">
      {relationships.map(rel=><section className="hlc-portal-project" key={`${rel.workspace_id}:${rel.lead_id}`}><div className="hlc-account-section-head"><div><span>PROJECT</span><h2>{rel.homeowner_name||"Your project"}</h2></div><strong>{rel.estimates.length+rel.jobs.length} records</strong></div><div className="hlc-portal-subsection"><h3>LeadScope estimates</h3>{!rel.estimates.length&&<p>No estimates shared yet.</p>}{rel.estimates.map(est=><article className="hlc-portal-row" key={est.id}><div><strong>{formatCurrency(Number(est.total))}</strong><span>{est.status}</span><ul>{est.lines.map(line=><li key={line.id}>{line.description} — {line.quantity} × {formatCurrency(Number(line.unit_cost))}</li>)}</ul></div>{est.status==="sent"&&<div className="hlc-portal-actions"><button disabled={busy} onClick={()=>void act(()=>decideHomeownerEstimate(est.id,"accepted"),"Estimate accepted.")}>Accept estimate</button><button disabled={busy} onClick={()=>void act(()=>decideHomeownerEstimate(est.id,"rejected"),"Estimate rejected.")}>Reject estimate</button></div>}</article>)}</div><div className="hlc-portal-subsection"><h3>Jobs & appointments</h3>{!rel.jobs.length&&<p>No jobs created yet.</p>}{rel.jobs.map(job=><article className="hlc-portal-row" key={job.id}><div><strong>{job.name}</strong><span>{job.status} · {formatCurrency(Number(job.contract_value))}</span>{!job.appointments.length?<p>No appointments scheduled.</p>:<ul>{job.appointments.map(appt=><li key={appt.id}>{new Date(appt.appointment_date).toLocaleString()} · {appt.status}</li>)}</ul>}</div></article>)}</div></section>)}
      <section id="resident-matches" className="hlc-portal-project"><div className="hlc-account-section-head"><div><span>MATCH</span><h2>Provider matches</h2></div><strong>{matches.length}</strong></div>{!matches.length?<p>No provider match has been proposed yet.</p>:matches.map(match=><article className="hlc-portal-row" key={match.id}><div><strong>{match.provider.company_name||match.provider.contact_name||"Service professional"}</strong><span>{match.provider.provider_type.replaceAll("_"," ")} · {match.provider.specialty||"Service details not recorded"}</span><p>{[match.provider.city,match.provider.state].filter(Boolean).join(", ")||"Service location not recorded"} · Verification: {match.provider.verification_status}</p>{match.rationale&&<p>{match.rationale}</p>}<p>Status: <strong>{match.status}</strong></p></div>{match.status==="proposed"&&<div className="hlc-portal-actions"><button disabled={busy} onClick={()=>void act(()=>decideHomeownerProviderMatch(match.id,"accepted"),"Provider match accepted.")}>Accept provider</button><button disabled={busy} onClick={()=>void act(()=>decideHomeownerProviderMatch(match.id,"declined"),"Provider match declined.")}>Decline provider</button></div>}</article>)}</section>
      <section id="resident-payments" className="hlc-portal-project"><div className="hlc-account-section-head"><div><span>PAYMENT</span><h2>Job payments</h2></div><strong>{payments.length}</strong></div>{!payments.length?<p>No job payment has been issued.</p>:payments.map(payment=><article className="hlc-portal-row" key={payment.id}><div><strong>{formatCurrency(Number(payment.amount))} {payment.currency.toUpperCase()}</strong><span>{payment.status}</span>{payment.failure_message&&<p role="alert">{payment.failure_message}</p>}</div><div className="hlc-portal-actions">{payment.checkout_url&&["pending","checkout_created","processing","failed"].includes(payment.status)&&<a href={payment.checkout_url} rel="noopener noreferrer">Secure checkout</a>}{payment.receipt_url&&<a href={payment.receipt_url} rel="noopener noreferrer">Receipt</a>}</div></article>)}</section>
      <section id="resident-reviews" className="hlc-portal-project"><div className="hlc-account-section-head"><div><span>REVIEW</span><h2>Completed-service reviews</h2></div><strong>{reviews.length}</strong></div>{eligibleReviews.length>0&&<form onSubmit={e=>{e.preventDefault();void act(()=>createHomeownerReview(reviewJobId,rating,reviewBody),"Review published.");setReviewBody("");}}><label>Completed job<select value={reviewJobId} onChange={e=>setReviewJobId(e.target.value)}>{eligibleReviews.map(job=><option key={job.id} value={job.id}>{job.name}</option>)}</select></label><label>Rating<select value={rating} onChange={e=>setRating(Number(e.target.value))}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} star{n===1?"":"s"}</option>)}</select></label><label>Your review<textarea required minLength={3} value={reviewBody} onChange={e=>setReviewBody(e.target.value)}/></label><button disabled={busy||!reviewJobId}>Publish review</button></form>}{!eligibleReviews.length&&!reviews.length&&<p>No completed job is currently eligible for review.</p>}{reviews.map(review=><article className="hlc-portal-row" key={review.id}><strong>{review.rating}/5</strong><span>{review.status}</span><p>{review.body}</p></article>)}</section>
      <section className="hlc-portal-project"><div className="hlc-account-section-head"><div><span>REFER / REPEAT</span><h2>Help someone else</h2></div><strong>{referrals.length}</strong></div>{referralLeadId?<form onSubmit={e=>{e.preventDefault();void act(()=>createHomeownerReferral(referralLeadId,referralEmail,referralNote),"Referral recorded.");setReferralEmail("");setReferralNote("");}}><p>Record a referral only. HLC will not claim that this action contacted or enrolled the referred person.</p><label>Email<input required type="email" value={referralEmail} onChange={e=>setReferralEmail(e.target.value)}/></label><label>Note<textarea value={referralNote} onChange={e=>setReferralNote(e.target.value)}/></label><button disabled={busy}>Record referral</button> <Link to="/request-service">Start another service request</Link></form>:<p>A linked service request is required before this account can attribute a referral.</p>}{referrals.map(ref=><article className="hlc-portal-row" key={ref.id}><strong>{ref.referred_email}</strong><span>{ref.status}</span>{ref.note&&<p>{ref.note}</p>}</article>)}</section>
      <section className="hlc-portal-project"><div className="hlc-account-section-head"><div><span>SHARED EVIDENCE</span><h2>Documents & media</h2></div><strong>{documents.length}</strong></div>{!documents.length?<p className="hlc-portal-state">No documents have been shared with you.</p>:documents.map(document=><article className="hlc-portal-file-row" key={document.id}><button type="button" onClick={()=>void openDocument(document)}>{document.filename}</button><span>{document.entity_type}</span></article>)}</section>
    </div>
  </main>;
}
