import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { createPartnerReferral, getPartnerPortalData, type PartnerPortalData } from "../../api/partners";
import { errorMessage } from "../../lib/errorMessage";

export default function PartnerPortal(){
  const[data,setData]=useState<PartnerPortalData|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");
  const[targetKind,setTargetKind]=useState<"resident"|"professional">("resident");const[name,setName]=useState("");const[email,setEmail]=useState("");const[phone,setPhone]=useState("");const[note,setNote]=useState("");
  const load=useCallback(async()=>{setError("");try{setData(await getPartnerPortalData());}catch(reason){setError(errorMessage(reason,"Unable to load partner access."));}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");setMessage("");try{await createPartnerReferral({targetKind,referredName:name,referredEmail:email,referredPhone:phone,note});setName("");setEmail("");setPhone("");setNote("");await load();setMessage("Referral recorded. HLC has not claimed contact or conversion until the status actually changes.");}catch(reason){setError(errorMessage(reason,"Unable to record the referral."));}finally{setBusy(false);}}
  return <main className="hlc-portal-workspace is-resident">
    <header className="hlc-portal-header"><div><p className="hlc-account-kicker">PARTNER PORTAL</p><h1>Referral workspace</h1><p>Record attributed referrals, see their current HLC status, and submit another referral without entering internal operations or contractor tools.</p></div><div className="hlc-portal-summary"><span><strong>{data?.referrals.length??0}</strong><small>Referrals</small></span><span><strong>{data?.referrals.filter(x=>x.status==="converted").length??0}</strong><small>Converted</small></span></div></header>
    <nav className="hlc-portal-actions" aria-label="Partner actions"><Link to="/partner-portal">Referrals</Link><Link to="/contact">Contact HLC</Link></nav>
    {loading&&<p className="hlc-portal-state">Loading partner workspace…</p>}{error&&<p role="alert" className="hlc-account-status is-error">{error}</p>}{message&&<p role="status" className="hlc-account-status is-success">{message}</p>}
    {data&&<section className="hlc-portal-project"><div className="hlc-account-section-head"><div><span>PARTNER SOURCE</span><h2>{data.source.organization_name||data.source.display_name}</h2></div><strong>{data.source.status}</strong></div><p>{data.source.contact_email||"Contact email not recorded"}</p></section>}
    {data&&<section className="hlc-portal-project"><div className="hlc-account-section-head"><div><span>NEW REFERRAL</span><h2>Refer a resident or professional</h2></div></div><form onSubmit={submit}><label>Referral type<select value={targetKind} onChange={e=>setTargetKind(e.target.value as "resident"|"professional")}><option value="resident">Resident / renter / homeowner</option><option value="professional">Service professional / business</option></select></label><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Phone<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Referral note<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><p>At least an email or phone number is required. Recording a referral does not send a message or enroll the referred person.</p><button disabled={busy}>{busy?"Recording…":"Record referral"}</button></form></section>}
    {data&&<section className="hlc-portal-project"><div className="hlc-account-section-head"><div><span>STATUS</span><h2>Referral history</h2></div><strong>{data.referrals.length}</strong></div>{!data.referrals.length?<p>No referrals recorded yet.</p>:data.referrals.map(item=><article className="hlc-portal-row" key={item.id}><div><strong>{item.referred_name||item.referred_email||item.referred_phone||"Referral"}</strong><span>{item.target_kind} · {item.status}</span><p>{[item.referred_email,item.referred_phone].filter(Boolean).join(" · ")}</p>{item.note&&<p>{item.note}</p>}<small>Recorded {new Date(item.created_at).toLocaleString()}</small></div></article>)}</section>}
  </main>;
}
