import { Link } from "react-router-dom";
import PublicSiteNav from "../components/PublicSiteNav";
import { pageImage } from "../config/publicPageImagery";
import "../styles/mockup-authority-20260924.css";

export type PathwayPageKind="residents"|"professionals"|"partners"|"community";
const content={
 residents:{eyebrow:"For Residents",title:"Home help should feel clear from the very first step.",lead:"Tell HomeLead Connect what the home needs. Keep the request, next step, and connection easier to understand from start through follow-through.",primary:"Request home service",primaryTo:"/request-service",secondary:"See how it works",secondaryTo:"/how-it-works",story:"A simple way to move the home forward.",storyBody:"Start with the need in front of you. HomeLead Connect helps organize the information and connection without making you figure out every trade, term, or next step alone.",steps:["Tell us what the home needs","Share useful project details","Connect with the right next step","Keep the journey together"],feature:"Better information before the work begins.",featureBody:"LeadScope helps organize project context, photos, measurements, scheduling, and request details so the next conversation starts clearer.",featureTo:"/leadscope",featureAction:"Explore LeadScope →",final:"Ready when you are? Start with the home in front of you."},
 professionals:{eyebrow:"For Professionals",title:"More opportunities. Real projects. One connected professional experience.",lead:"Bring your service business into the HomeLead Connect network with a clearer path from professional presence to opportunity, scheduling, work, and follow-through.",primary:"Apply as a Professional",primaryTo:"/professional-application",secondary:"How professional access works",secondaryTo:"/contractors",story:"Built around the way real service work moves.",storyBody:"Professional access should make the work easier to see and easier to follow—not turn your business into another dashboard full of noise.",steps:["Build your professional presence","Receive relevant opportunity context","Coordinate schedules and communication","Carry work through follow-through"],feature:"Your business stays yours. The workflow gets more connected.",featureBody:"HomeLead Connect supports independent professionals and service businesses while keeping roles, customer context, and responsibility clear.",featureTo:"/professional-application",featureAction:"View professional application →",final:"Put your service business inside a more connected workflow."},
 partners:{eyebrow:"For Partners",title:"Useful connections built around clarity, context, and trust.",lead:"Create referral and community relationships that help people reach the right home-service resources without blurring who is responsible for what.",primary:"Start a partnership conversation",primaryTo:"/contact",secondary:"See the network",secondaryTo:"/community",story:"A partnership should make the experience clearer.",storyBody:"HomeLead Connect keeps identities distinct while supporting useful handoffs between organizations, residents, professionals, and community resources.",steps:["Identify the opportunity","Make the connection understandable","Share appropriate context","Keep responsibilities clear"],feature:"Relationships that strengthen the ecosystem.",featureBody:"Partners can help residents and communities discover resources while each organization remains responsible for its own services and representations.",featureTo:"/contact",featureAction:"Contact HomeLead Connect →",final:"Build the right connection without creating confusion."},
 community:{eyebrow:"Community",title:"The people around the work matter too.",lead:"Bring local knowledge, resident experience, professional insight, resources, reviews, referrals, and neighborhood connection into one shared community environment.",primary:"Explore Community",primaryTo:"/community",secondary:"Browse services",secondaryTo:"/services",story:"Stronger homes connect to stronger communities.",storyBody:"Community is where useful experience can travel beyond a single project—helping neighbors, professionals, and local relationships learn and connect.",steps:["Share useful local context","Learn from resident experience","Discover professional insight","Connect people with resources"],feature:"Local knowledge belongs in the experience.",featureBody:"HomeLead Connect creates room for the conversations and resources around home service, not only the transaction itself.",featureTo:"/community",featureAction:"Explore community resources →",final:"Help useful knowledge and opportunity move through the community."}
} as const;
export default function PathwayPage({pathway}:{pathway:PathwayPageKind}){const c=content[pathway];const imageKey=pathway==="residents"?"homeowners":pathway==="professionals"?"professionals":pathway==="partners"?"partners":"community";const visual=pageImage(imageKey);return <main className="hcx-shell hcx-pathway" data-pathway={pathway}><PublicSiteNav/><section className="hcx-pathway-hero"><div className="hcx-pathway-copy"><p className="hcx-eyebrow">{c.eyebrow}</p><h1>{c.title}</h1><p>{c.lead}</p><div className="hcx-actions"><Link to={c.primaryTo}>{c.primary}</Link><Link to={c.secondaryTo}>{c.secondary} →</Link></div></div><div className="hcx-pathway-media"><img src={visual.src} alt={visual.alt}/></div></section><section className="hcx-story"><p className="hcx-eyebrow">The connected path</p><h2>{c.story}</h2><p>{c.storyBody}</p><div className="hcx-flow">{c.steps.map((step,index)=><div key={step}><span>0{index+1}</span><strong>{step}</strong></div>)}</div></section><section className="hcx-feature"><img src={visual.src} alt="" aria-hidden="true"/><div className="hcx-feature-copy"><p className="hcx-eyebrow">HomeLead Connect</p><h2>{c.feature}</h2><p>{c.featureBody}</p><Link className="hcx-text-link" to={c.featureTo}>{c.featureAction}</Link></div></section><section className="hcx-final"><h2>{c.final}</h2><Link to={c.primaryTo}>{c.primary} →</Link></section></main>}
