import "./styles/mockup-authority-20260924.css";
import "./styles/home-no-glow-20260925.css";
import "./styles/public-full-bleed-20260925.css";
import { APP_ORIGIN, PUBLIC_ORIGIN } from "./config/siteOrigins";

const pathways=[["resident","For Residents","Find help with the home in front of you—and keep the next step clear.","/homeowners","Find resident support →"],["professional","For Professionals","Grow your business, get more opportunities, and do your best work.","/professionals","Explore professional access →"],["partner","For Partners","Create referral relationships that respect people, context, and consent.","/partners","Explore partner opportunities →"],["community","For Community","Find the people and resources that help build stronger neighborhoods.","/community","Explore community resources →"]] as const;
const primary=[["Home","/"],["About","/about"],["Residents","/homeowners"],["Professionals","/professionals"],["Partners","/partners"],["Community","/community"],["Resources","/services"]] as const;
const secondary=[["Services","/services"],["Contact","/contact"],["Accessibility","/accessibility"],["Platform Disclosure","/platform-disclosure"],["Privacy","/privacy"],["Terms","/terms"]] as const;
function make<K extends keyof HTMLElementTagNameMap>(tag:K,className?:string,text?:string){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node}
function link(href:string,className?:string,text?:string){const node=make("a",className,text);node.href=href;return node}
export function mountStandalonePublicHome(root:HTMLElement){root.replaceChildren();const main=make("main","hcx-shell");const header=make("header","hlc-board-nav");const navInner=make("div","hlc-board-nav-inner");const trigger=make("button","hlc-board-brand");trigger.type="button";trigger.setAttribute("aria-label","Open HomeLead Connect menu");trigger.setAttribute("aria-expanded","false");trigger.setAttribute("aria-controls","hlc-public-menu");const logo=make("img","hlc-navbar-master-logo");logo.src="/hlc-logo-ui.png";logo.alt="";logo.setAttribute("aria-hidden","true");trigger.append(logo,make("span","hlc-brand-accessible-label","HomeLead Connect"));const desktop=make("nav","hlc-public-desktop-links");desktop.setAttribute("aria-label","Public pages");for(const[label,path]of primary.slice(1))desktop.append(link(`${PUBLIC_ORIGIN}${path}`,undefined,label));const actions=make("div","hlc-board-actions");actions.append(link(`${APP_ORIGIN}/login`,"hlc-board-login","Sign In"),link(`${APP_ORIGIN}/register`,"hlc-board-cta","Get Started"));navInner.append(trigger,desktop,actions);const backdrop=make("div","hlc-public-menu-backdrop");backdrop.hidden=true;const panel=make("nav","hlc-public-menu-panel");panel.id="hlc-public-menu";panel.setAttribute("aria-label","HomeLead Connect menu");const p=make("div","hlc-public-menu-primary");for(const[label,path]of primary)p.append(link(`${PUBLIC_ORIGIN}${path}`,undefined,label));const s=make("div","hlc-public-menu-secondary");for(const[label,path]of secondary)s.append(link(`${PUBLIC_ORIGIN}${path}`,undefined,label));const a=make("div","hlc-public-menu-account");a.append(link(`${APP_ORIGIN}/login`,undefined,"Sign In"),link(`${APP_ORIGIN}/register`,undefined,"Get Started"));panel.append(p,s,a);backdrop.append(panel);header.append(navInner,backdrop);
const hero=make("section","hcx-home-hero");const picture=make("picture");const img=make("img");img.src="/hlc-homepage-hero-welcome-doorway-20260917.webp";img.alt="";img.setAttribute("aria-hidden","true");img.setAttribute("fetchpriority","high");picture.append(img);const copy=make("div","hcx-home-copy");copy.append(make("p","hcx-kicker","The HomeLead Connect ecosystem"));const h1=make("h1");h1.append("A stronger community ",make("span",undefined,"starts here."));copy.append(h1,make("p","hcx-home-tagline","Connecting homes. Creating opportunities."),make("p","hcx-home-intro","The people. The services. The partnerships. All in one place to help our communities move forward."));const script=make("p","hcx-script","Stronger Homes. Brighter Futures.");script.append(make("small",undefined,"Harrisburg, PA"));hero.append(picture,copy,script);
const pathSection=make("section","hcx-pathway-links");pathSection.setAttribute("aria-label","HomeLead Connect pathways");for(const[key,title,body,href,action]of pathways){const item=link(href,"hcx-pathway-link");item.dataset.tone=key;const content=make("span");content.append(make("strong",undefined,title),make("span",undefined,body),make("b",undefined,action));item.append(content);pathSection.append(item)}const mission=make("section","hcx-mission");mission.append(make("p",undefined,"Connecting Homes. Creating Opportunities."));const missionItems=make("div");for(const label of["Stronger Homes","More Opportunities","Thriving Communities","Brighter Futures"])missionItems.append(make("span",undefined,label));mission.append(missionItems);main.append(header,hero,pathSection,mission);
const footer=make("footer","hlc-public-footer");const footerLogo=make("img","hlc-public-footer-master-logo");footerLogo.src="/hlc-logo-ui.png";footerLogo.alt="HomeLead Connect LLC";footer.append(footerLogo,make("strong",undefined,"HomeLead Connect"),make("span",undefined,"Connecting Homes. Creating Opportunities."));const legal=make("nav");legal.setAttribute("aria-label","Legal and accessibility");for(const[label,path]of[["Privacy","/privacy"],["Terms","/terms"],["Accessibility","/accessibility"],["Platform disclosure","/platform-disclosure"]]as const)legal.append(link(`${PUBLIC_ORIGIN}${path}`,undefined,label));footer.append(legal,make("small",undefined,`© ${new Date().getFullYear()} HomeLead Connect LLC`));root.append(main,footer);
const close=()=>{backdrop.hidden=true;trigger.setAttribute("aria-expanded","false");document.body.style.overflow="";trigger.focus()};const open=()=>{backdrop.hidden=false;trigger.setAttribute("aria-expanded","true");document.body.style.overflow="hidden"};trigger.addEventListener("click",()=>backdrop.hidden?open():close());backdrop.addEventListener("mousedown",e=>{if(e.target===backdrop)close()});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!backdrop.hidden)close()})}
