-- Restore canonical HomeLead Connect analytics/KPI contracts that are present in the migration chain
-- but absent from the production public schema. This intentionally reuses the established contracts.

create table if not exists public.analytics_site_sources (
  hostname text primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  created_at timestamptz not null default now(),
  check (hostname = lower(hostname) and length(hostname) between 3 and 255)
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  workspace_id uuid references public.workspaces(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  session_id uuid not null,
  event_name text not null,
  path text not null,
  hostname text,
  referrer_host text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  check (event_name ~ '^[a-z][a-z0-9_]{1,63}$'),
  check (length(path) between 1 and 500),
  check (hostname is null or length(hostname) <= 255),
  check (referrer_host is null or length(referrer_host) <= 255),
  check (jsonb_typeof(metadata) = 'object'),
  check (pg_column_size(metadata) <= 4096)
);

alter table public.analytics_site_sources enable row level security;
alter table public.analytics_events enable row level security;
revoke all on public.analytics_site_sources from anon, authenticated;
revoke all on public.analytics_events from anon, authenticated;
grant all on public.analytics_site_sources to service_role;
grant all on public.analytics_events to service_role;

create index if not exists analytics_events_workspace_created_idx on public.analytics_events(workspace_id, created_at desc);
create index if not exists analytics_events_session_created_idx on public.analytics_events(session_id, created_at desc);
create index if not exists analytics_events_event_created_idx on public.analytics_events(event_name, created_at desc);
create index if not exists analytics_events_path_created_idx on public.analytics_events(path, created_at desc);
create index if not exists analytics_events_user_id_idx on public.analytics_events(user_id);
create index if not exists analytics_site_sources_workspace_id_idx on public.analytics_site_sources(workspace_id);

insert into public.analytics_site_sources(hostname, workspace_id)
select 'app.homeleadconnect.org', bp.workspace_id
from public.business_profile bp
where lower(coalesce(bp.business_name,'')) like 'homelead connect%'
order by bp.created_at asc limit 1
on conflict (hostname) do update set workspace_id=excluded.workspace_id;

create or replace function public.record_hlc_analytics_event(
  p_session_id uuid,
  p_event_name text,
  p_path text,
  p_hostname text default null,
  p_referrer_host text default null,
  p_metadata jsonb default '{}'::jsonb
) returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_user uuid := auth.uid();
  v_workspace uuid;
  v_id bigint;
  v_hostname text := lower(nullif(btrim(p_hostname),''));
begin
  if p_session_id is null then raise exception 'session id required'; end if;
  if p_event_name is null or p_event_name !~ '^[a-z][a-z0-9_]{1,63}$' then raise exception 'invalid analytics event'; end if;
  if p_path is null or left(p_path,1) <> '/' or length(p_path) > 500 or position('?' in p_path) > 0 or position('#' in p_path) > 0 then raise exception 'invalid analytics path'; end if;
  if p_metadata is null or jsonb_typeof(p_metadata) <> 'object' or pg_column_size(p_metadata) > 4096 then raise exception 'invalid analytics metadata'; end if;

  if v_user is not null then
    select p.workspace_id into v_workspace from public.profiles p where p.user_id=v_user and p.workspace_id is not null limit 1;
    if v_workspace is null then
      select wm.workspace_id into v_workspace from public.workspace_members wm where wm.user_id=v_user order by wm.created_at asc limit 1;
    end if;
  end if;

  if v_hostname is not null then
    select s.workspace_id into v_workspace
    from public.analytics_site_sources s
    where s.hostname=v_hostname and (v_user is null or v_workspace is null or s.workspace_id=v_workspace);
  end if;

  if v_workspace is null then return null; end if;

  if exists (
    select 1 from public.analytics_events e
    where e.session_id=p_session_id and e.event_name=p_event_name and e.path=p_path
      and e.created_at>now()-interval '2 seconds'
  ) then return null; end if;

  insert into public.analytics_events(workspace_id,user_id,session_id,event_name,path,hostname,referrer_host,metadata)
  values(v_workspace,v_user,p_session_id,p_event_name,p_path,v_hostname,left(nullif(btrim(p_referrer_host),''),255),p_metadata)
  returning id into v_id;
  return v_id;
end;
$$;
revoke all on function public.record_hlc_analytics_event(uuid,text,text,text,text,jsonb) from public;
grant execute on function public.record_hlc_analytics_event(uuid,text,text,text,text,jsonb) to anon, authenticated;

create or replace function public.get_hlc_analytics_summary(p_days integer default 30)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare
  v_user uuid:=auth.uid(); v_workspace uuid; v_days integer:=greatest(1,least(coalesce(p_days,30),365));
  v_since timestamptz; v_result jsonb;
begin
  if v_user is null then raise exception 'authentication required' using errcode='42501'; end if;
  select p.workspace_id into v_workspace from public.profiles p where p.user_id=v_user and p.workspace_id is not null limit 1;
  if v_workspace is null then select wm.workspace_id into v_workspace from public.workspace_members wm where wm.user_id=v_user order by wm.created_at asc limit 1; end if;
  if v_workspace is null or not exists(select 1 from public.workspace_members wm where wm.workspace_id=v_workspace and wm.user_id=v_user) then raise exception 'workspace access denied' using errcode='42501'; end if;
  v_since:=now()-make_interval(days=>v_days);
  select jsonb_build_object(
    'days',v_days,
    'page_views',count(*) filter(where event_name='page_view'),
    'sessions',count(distinct session_id),
    'authenticated_sessions',count(distinct session_id) filter(where user_id is not null),
    'visitor_sessions',count(distinct session_id) filter(where user_id is null),
    'leadscope_views',count(*) filter(where path='/estimator' and event_name='page_view'),
    'material_store_clicks',count(*) filter(where event_name='material_store_open'),
    'sign_in_starts',count(*) filter(where event_name='sign_in_started'),
    'service_request_starts',count(*) filter(where event_name='service_request_started'),
    'top_paths',coalesce((select jsonb_agg(jsonb_build_object('path',x.path,'views',x.views) order by x.views desc) from (select e.path,count(*)::bigint views from public.analytics_events e where e.workspace_id=v_workspace and e.created_at>=v_since and e.event_name='page_view' group by e.path order by views desc limit 8)x),'[]'::jsonb),
    'events',coalesce((select jsonb_agg(jsonb_build_object('event',x.event_name,'count',x.total) order by x.total desc) from (select e.event_name,count(*)::bigint total from public.analytics_events e where e.workspace_id=v_workspace and e.created_at>=v_since group by e.event_name order by total desc limit 12)x),'[]'::jsonb)
  ) into v_result from public.analytics_events e where e.workspace_id=v_workspace and e.created_at>=v_since;
  return coalesce(v_result,'{}'::jsonb);
end;
$$;
revoke all on function public.get_hlc_analytics_summary(integer) from public;
grant execute on function public.get_hlc_analytics_summary(integer) to authenticated;

create or replace function public.get_hlc_business_kpis(p_days integer default 30)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare
  v_user uuid:=auth.uid(); v_workspace uuid; v_days integer:=greatest(1,least(coalesce(p_days,30),365));
  v_since timestamptz:=now()-make_interval(days=>greatest(1,least(coalesce(p_days,30),365)));
  v_leads bigint:=0; v_estimates bigint:=0; v_accepted_estimates bigint:=0; v_converted_estimates bigint:=0;
  v_jobs bigint:=0; v_assignments bigint:=0; v_accepted_assignments bigint:=0; v_appointments bigint:=0;
  v_completed_appointments bigint:=0; v_pending_followups bigint:=0; v_overdue_followups bigint:=0;
  v_calls bigint:=0; v_missed_calls bigint:=0; v_voicemails bigint:=0; v_pipeline_value numeric:=0; v_job_value numeric:=0;
begin
  if v_user is null then raise exception 'authentication required' using errcode='42501'; end if;
  select p.workspace_id into v_workspace from public.profiles p where p.user_id=v_user and p.workspace_id is not null limit 1;
  if v_workspace is null then select wm.workspace_id into v_workspace from public.workspace_members wm where wm.user_id=v_user order by wm.created_at asc limit 1; end if;
  if v_workspace is null or not exists(select 1 from public.workspace_members wm where wm.workspace_id=v_workspace and wm.user_id=v_user) then raise exception 'workspace access denied' using errcode='42501'; end if;
  select count(*) into v_leads from public.leads where workspace_id=v_workspace and created_at>=v_since and coalesce(archived,false)=false;
  select count(*),count(*) filter(where status='accepted'),count(*) filter(where status='converted'),coalesce(sum(total) filter(where status in ('sent','accepted')),0)
    into v_estimates,v_accepted_estimates,v_converted_estimates,v_pipeline_value from public.estimates where workspace_id=v_workspace and created_at>=v_since;
  select count(*),coalesce(sum(contract_value),0) into v_jobs,v_job_value from public.crm_jobs where workspace_id=v_workspace and created_at>=v_since;
  select count(*),count(*) filter(where status='accepted') into v_assignments,v_accepted_assignments from public.job_assignments where workspace_id=v_workspace and created_at>=v_since;
  select count(*),count(*) filter(where status='completed') into v_appointments,v_completed_appointments from public.appointments where workspace_id=v_workspace and created_at>=v_since;
  select count(*) filter(where f.status='pending'),count(*) filter(where f.status='pending' and f.scheduled_for<now()) into v_pending_followups,v_overdue_followups from public.follow_ups f join public.leads l on l.id_uuid=f.lead_id where l.workspace_id=v_workspace and f.created_at>=v_since;
  select count(*),count(*) filter(where normalized_state='no_answer'),count(*) filter(where normalized_state='voicemail') into v_calls,v_missed_calls,v_voicemails from public.call_sessions where workspace_id=v_workspace and started_at>=v_since;
  return jsonb_build_object(
    'days',v_days,'leads',v_leads,'estimates',v_estimates,'accepted_estimates',v_accepted_estimates,'converted_estimates',v_converted_estimates,
    'lead_to_estimate_rate',case when v_leads>0 then round((v_estimates::numeric/v_leads::numeric)*100,1) else 0 end,
    'estimate_acceptance_rate',case when v_estimates>0 then round(((v_accepted_estimates+v_converted_estimates)::numeric/v_estimates::numeric)*100,1) else 0 end,
    'estimate_to_job_rate',case when v_estimates>0 then round((v_converted_estimates::numeric/v_estimates::numeric)*100,1) else 0 end,
    'jobs',v_jobs,'job_value',v_job_value,'open_estimate_value',v_pipeline_value,'assignments',v_assignments,'accepted_assignments',v_accepted_assignments,
    'assignment_acceptance_rate',case when v_assignments>0 then round((v_accepted_assignments::numeric/v_assignments::numeric)*100,1) else 0 end,
    'appointments',v_appointments,'completed_appointments',v_completed_appointments,'pending_followups',v_pending_followups,'overdue_followups',v_overdue_followups,
    'calls',v_calls,'missed_calls',v_missed_calls,'voicemails',v_voicemails
  );
end;
$$;
revoke all on function public.get_hlc_business_kpis(integer) from public;
grant execute on function public.get_hlc_business_kpis(integer) to authenticated;

create or replace function public.get_hlc_growth_summary(p_days integer default 30)
returns jsonb language plpgsql security definer set search_path='' as $$
declare
  v_workspace_id uuid; v_role text;
  v_since timestamptz:=now()-make_interval(days=>greatest(1,least(coalesce(p_days,30),365)));
  v_total_leads integer:=0; v_unknown_leads integer:=0; v_referrals integer:=0;
  v_sources jsonb:='[]'::jsonb; v_referral_statuses jsonb:='[]'::jsonb;
begin
  if (select auth.uid()) is null then raise exception 'Authentication is required.' using errcode='42501'; end if;
  select p.workspace_id,lower(coalesce(p.role,'')) into v_workspace_id,v_role from public.profiles p where p.user_id=(select auth.uid());
  if v_workspace_id is null or v_role not in ('owner','manager') or not exists(select 1 from public.workspace_members wm where wm.workspace_id=v_workspace_id and wm.user_id=(select auth.uid())) then raise exception 'Growth analytics access requires an owner or manager role.' using errcode='42501'; end if;
  select count(*)::int,count(*) filter(where nullif(btrim(coalesce(l.source,'')),'') is null or lower(btrim(l.source))='unknown')::int into v_total_leads,v_unknown_leads from public.leads l where l.workspace_id=v_workspace_id and l.created_at>=v_since and coalesce(l.archived,false)=false;
  select coalesce(jsonb_agg(jsonb_build_object('source',source_key,'lead_count',lead_count) order by lead_count desc,source_key),'[]'::jsonb) into v_sources from (select case when nullif(btrim(coalesce(l.source,'')),'') is null then 'unknown' else lower(btrim(l.source)) end source_key,count(*)::int lead_count from public.leads l where l.workspace_id=v_workspace_id and l.created_at>=v_since and coalesce(l.archived,false)=false group by 1)s;
  select count(*)::int into v_referrals from public.community_referrals r where r.workspace_id=v_workspace_id and r.created_at>=v_since;
  select coalesce(jsonb_agg(jsonb_build_object('status',status_key,'count',referral_count) order by referral_count desc,status_key),'[]'::jsonb) into v_referral_statuses from (select lower(coalesce(nullif(btrim(r.status),''),'unknown')) status_key,count(*)::int referral_count from public.community_referrals r where r.workspace_id=v_workspace_id and r.created_at>=v_since group by 1)rs;
  return jsonb_build_object('days',greatest(1,least(coalesce(p_days,30),365)),'total_leads',v_total_leads,'unknown_source_leads',v_unknown_leads,'known_source_leads',greatest(v_total_leads-v_unknown_leads,0),'attribution_known_rate',case when v_total_leads=0 then 0 else round(((v_total_leads-v_unknown_leads)::numeric/v_total_leads::numeric)*100,1) end,'sources',v_sources,'referrals',v_referrals,'referral_statuses',v_referral_statuses);
end;
$$;
revoke all on function public.get_hlc_growth_summary(integer) from public;
revoke all on function public.get_hlc_growth_summary(integer) from anon;
grant execute on function public.get_hlc_growth_summary(integer) to authenticated;
grant execute on function public.get_hlc_growth_summary(integer) to service_role;
