create table public.portal_invitations (
  id uuid primary key default gen_random_uuid(),
  token_hash bytea not null unique,
  portal_role text not null check (portal_role in ('homeowner', 'contractor')),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  lead_id bigint references public.leads(id) on delete cascade,
  contractor_id bigint references public.contractors(id) on delete cascade,
  intended_email text not null,
  issued_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  accepted_at timestamptz,
  accepted_by uuid references auth.users(id),
  revoked_at timestamptz,
  check (
    (portal_role = 'homeowner' and lead_id is not null and contractor_id is null)
    or (portal_role = 'contractor' and contractor_id is not null and lead_id is null)
  )
);

create index portal_invitations_workspace_idx on public.portal_invitations(workspace_id, created_at desc);
create index portal_invitations_open_idx on public.portal_invitations(expires_at)
  where accepted_at is null and revoked_at is null;

create table public.homeowner_portal_links (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  lead_id bigint not null references public.leads(id) on delete cascade,
  invitation_id uuid not null unique references public.portal_invitations(id),
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);

create unique index homeowner_portal_links_active_unique
  on public.homeowner_portal_links(user_id, workspace_id, lead_id) where revoked_at is null;
create index homeowner_portal_links_user_idx
  on public.homeowner_portal_links(user_id, workspace_id) where revoked_at is null;

create table public.contractor_portal_links (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  contractor_id bigint not null references public.contractors(id) on delete cascade,
  invitation_id uuid not null unique references public.portal_invitations(id),
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);

create unique index contractor_portal_links_active_unique
  on public.contractor_portal_links(user_id, workspace_id, contractor_id) where revoked_at is null;
create index contractor_portal_links_user_idx
  on public.contractor_portal_links(user_id, workspace_id, contractor_id) where revoked_at is null;

create table public.portal_access_events (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  actor_user_id uuid not null references auth.users(id),
  portal_role text not null check (portal_role in ('homeowner', 'contractor')),
  action text not null,
  entity_type text not null,
  entity_id text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index portal_access_events_workspace_idx
  on public.portal_access_events(workspace_id, created_at desc);
create index portal_access_events_actor_idx
  on public.portal_access_events(actor_user_id, created_at desc);

alter table public.portal_invitations enable row level security;
alter table public.homeowner_portal_links enable row level security;
alter table public.contractor_portal_links enable row level security;
alter table public.portal_access_events enable row level security;

create policy portal_invitations_workspace_select on public.portal_invitations
for select to authenticated using (
  exists (select 1 from public.workspace_members wm
    where wm.workspace_id = portal_invitations.workspace_id and wm.user_id = auth.uid())
);

create policy homeowner_links_self_select on public.homeowner_portal_links
for select to authenticated using (user_id = auth.uid() and revoked_at is null);
create policy homeowner_links_workspace_select on public.homeowner_portal_links
for select to authenticated using (
  exists (select 1 from public.workspace_members wm
    where wm.workspace_id = homeowner_portal_links.workspace_id and wm.user_id = auth.uid())
);

create policy contractor_links_self_select on public.contractor_portal_links
for select to authenticated using (user_id = auth.uid() and revoked_at is null);
create policy contractor_links_workspace_select on public.contractor_portal_links
for select to authenticated using (
  exists (select 1 from public.workspace_members wm
    where wm.workspace_id = contractor_portal_links.workspace_id and wm.user_id = auth.uid())
);

create policy portal_events_actor_select on public.portal_access_events
for select to authenticated using (actor_user_id = auth.uid());
create policy portal_events_workspace_select on public.portal_access_events
for select to authenticated using (
  exists (select 1 from public.workspace_members wm
    where wm.workspace_id = portal_access_events.workspace_id and wm.user_id = auth.uid())
);

grant select on public.portal_invitations, public.homeowner_portal_links,
  public.contractor_portal_links, public.portal_access_events to authenticated;
grant all on public.portal_invitations, public.homeowner_portal_links,
  public.contractor_portal_links, public.portal_access_events to service_role;
grant usage, select on sequence public.portal_access_events_id_seq to authenticated, service_role;

create or replace function public.create_portal_invitation(
  p_issued_by uuid,
  p_portal_role text,
  p_target_id text,
  p_intended_email text,
  p_expires_in_minutes integer default 60
)
returns table(invitation_id uuid, invitation_token text, intended_email text, portal_role text)
language plpgsql security definer set search_path = '' as $$
declare
  v_workspace_id uuid;
  v_lead_id bigint;
  v_contractor_id bigint;
  v_token text;
  v_invitation_id uuid;
begin
  if p_issued_by is null then raise exception 'Invitation issuer is required.' using errcode='42501'; end if;
  if lower(p_portal_role) not in ('homeowner','contractor') then raise exception 'Invalid portal role.' using errcode='22023'; end if;
  if p_intended_email is null or btrim(p_intended_email) !~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then
    raise exception 'Enter a valid invitation email.' using errcode='22023';
  end if;
  if p_expires_in_minutes < 10 or p_expires_in_minutes > 1440 then raise exception 'Invalid invitation lifetime.' using errcode='22023'; end if;

  if lower(p_portal_role) = 'homeowner' then
    v_lead_id := p_target_id::bigint;
    select l.workspace_id into v_workspace_id from public.leads l where l.id=v_lead_id;
  else
    v_contractor_id := p_target_id::bigint;
    select c.workspace_id into v_workspace_id from public.contractors c where c.id=v_contractor_id;
  end if;
  if v_workspace_id is null then raise exception 'Invitation target not found.' using errcode='P0002'; end if;
  if not exists (select 1 from public.workspace_members wm where wm.workspace_id=v_workspace_id and wm.user_id=p_issued_by) then
    raise exception 'You cannot invite users to that workspace.' using errcode='42501';
  end if;

  v_token := encode(extensions.gen_random_bytes(32),'hex');
  insert into public.portal_invitations(
    token_hash,portal_role,workspace_id,lead_id,contractor_id,intended_email,issued_by,expires_at
  ) values (
    extensions.digest(v_token,'sha256'),lower(p_portal_role),v_workspace_id,v_lead_id,v_contractor_id,
    lower(btrim(p_intended_email)),p_issued_by,now()+make_interval(mins=>p_expires_in_minutes)
  ) returning id into v_invitation_id;

  insert into public.portal_access_events(workspace_id,actor_user_id,portal_role,action,entity_type,entity_id)
  values(v_workspace_id,p_issued_by,lower(p_portal_role),'invitation_created','portal_invitation',v_invitation_id::text);
  return query select v_invitation_id,v_token,lower(btrim(p_intended_email)),lower(p_portal_role);
end; $$;

create or replace function public.revoke_portal_invitation(p_invitation_id uuid)
returns void language plpgsql security definer set search_path = '' as $$
declare v_inv public.portal_invitations%rowtype;
begin
  if auth.uid() is null then raise exception 'Authentication is required.' using errcode='42501'; end if;
  select * into v_inv from public.portal_invitations where id=p_invitation_id for update;
  if not found then raise exception 'Invitation not found.' using errcode='P0002'; end if;
  if not exists (select 1 from public.workspace_members wm
    where wm.workspace_id=v_inv.workspace_id and wm.user_id=auth.uid()) then
    raise exception 'You cannot revoke that invitation.' using errcode='42501';
  end if;
  if v_inv.accepted_at is not null then raise exception 'An accepted invitation cannot be revoked.' using errcode='22023'; end if;
  if v_inv.revoked_at is null then
    update public.portal_invitations set revoked_at=now() where id=v_inv.id;
    insert into public.portal_access_events(workspace_id,actor_user_id,portal_role,action,entity_type,entity_id)
    values(v_inv.workspace_id,auth.uid(),v_inv.portal_role,'invitation_revoked','portal_invitation',v_inv.id::text);
  end if;
end; $$;

create or replace function public.accept_portal_invitation(p_invitation_token text)
returns table(portal_role text, workspace_id uuid, target_id text)
language plpgsql security definer set search_path = '' as $$
declare
  v_inv public.portal_invitations%rowtype;
  v_email text;
  v_target text;
begin
  if auth.uid() is null then raise exception 'Authentication is required.' using errcode='42501'; end if;
  select lower(email) into v_email from auth.users where id=auth.uid();
  select * into v_inv from public.portal_invitations
    where token_hash=extensions.digest(p_invitation_token,'sha256') for update;
  if not found then raise exception 'Invitation is invalid.' using errcode='22023'; end if;
  if v_inv.revoked_at is not null then raise exception 'Invitation was revoked.' using errcode='42501'; end if;
  if v_inv.accepted_at is not null then raise exception 'Invitation was already used.' using errcode='42501'; end if;
  if v_inv.expires_at <= now() then raise exception 'Invitation has expired.' using errcode='42501'; end if;
  if v_email is distinct from lower(v_inv.intended_email) then raise exception 'Sign in with the invited email address.' using errcode='42501'; end if;

  if v_inv.portal_role='homeowner' then
    insert into public.homeowner_portal_links(user_id,workspace_id,lead_id,invitation_id)
    values(auth.uid(),v_inv.workspace_id,v_inv.lead_id,v_inv.id);
    v_target := v_inv.lead_id::text;
  else
    insert into public.contractor_portal_links(user_id,workspace_id,contractor_id,invitation_id)
    values(auth.uid(),v_inv.workspace_id,v_inv.contractor_id,v_inv.id);
    v_target := v_inv.contractor_id::text;
  end if;
  update public.portal_invitations set accepted_at=now(),accepted_by=auth.uid() where id=v_inv.id;
  insert into public.portal_access_events(workspace_id,actor_user_id,portal_role,action,entity_type,entity_id)
  values(v_inv.workspace_id,auth.uid(),v_inv.portal_role,'invitation_accepted','portal_invitation',v_inv.id::text);
  return query select v_inv.portal_role,v_inv.workspace_id,v_target;
end; $$;

create or replace function public.get_homeowner_portal_data()
returns jsonb language sql security definer set search_path = '' stable as $$
  select coalesce(jsonb_agg(jsonb_build_object(
    'workspace_id',h.workspace_id,'lead_id',h.lead_id,'homeowner_name',l.full_name,
    'estimates',(select coalesce(jsonb_agg(jsonb_build_object(
      'id',e.id,'status',e.status,'subtotal',e.subtotal,'markup_amount',e.markup_amount,'total',e.total,
      'created_at',e.created_at,'lines',(select coalesce(jsonb_agg(jsonb_build_object(
        'id',el.id,'description',el.description,'quantity',el.quantity,'unit_cost',el.unit_cost,'sort_order',el.sort_order
      ) order by el.sort_order),'[]'::jsonb) from public.estimate_lines el where el.estimate_id=e.id)
    ) order by e.created_at desc),'[]'::jsonb) from public.estimates e where e.workspace_id=h.workspace_id and e.lead_id=h.lead_id),
    'jobs',(select coalesce(jsonb_agg(jsonb_build_object(
      'id',j.id,'name',j.name,'status',j.status,'contract_value',j.contract_value,'created_at',j.created_at,
      'appointments',(select coalesce(jsonb_agg(jsonb_build_object(
        'id',a.id,'appointment_date',a.appointment_date,'appointment_end_at',to_jsonb(a)->'appointment_end_at','status',a.status
      ) order by a.appointment_date),'[]'::jsonb) from public.appointments a where a.job_id=j.id)
    ) order by j.created_at desc),'[]'::jsonb) from public.crm_jobs j where j.workspace_id=h.workspace_id and j.lead_id=h.lead_id)
  )),'[]'::jsonb)
  from public.homeowner_portal_links h join public.leads l on l.id=h.lead_id
  where h.user_id=auth.uid() and h.revoked_at is null;
$$;

create or replace function public.homeowner_decide_estimate(p_estimate_id uuid,p_decision text)
returns text language plpgsql security definer set search_path = '' as $$
declare v_workspace uuid; v_status text;
begin
  if lower(p_decision) not in ('accepted','rejected') then raise exception 'Invalid estimate decision.' using errcode='22023'; end if;
  select e.workspace_id,e.status into v_workspace,v_status from public.estimates e
  where e.id=p_estimate_id and exists(select 1 from public.homeowner_portal_links h
    where h.user_id=auth.uid() and h.workspace_id=e.workspace_id and h.lead_id=e.lead_id and h.revoked_at is null)
  for update;
  if not found then raise exception 'Estimate not available.' using errcode='42501'; end if;
  if v_status <> 'sent' then raise exception 'Only a sent estimate can be accepted or rejected.' using errcode='22023'; end if;
  update public.estimates set status=lower(p_decision) where id=p_estimate_id;
  insert into public.portal_access_events(workspace_id,actor_user_id,portal_role,action,entity_type,entity_id)
  values(v_workspace,auth.uid(),'homeowner','estimate_'||lower(p_decision),'estimate',p_estimate_id::text);
  return lower(p_decision);
end; $$;

create or replace function public.get_contractor_portal_data()
returns jsonb language sql security definer set search_path = '' stable as $$
  select jsonb_build_object(
    'links',coalesce((select jsonb_agg(jsonb_build_object('workspace_id',cpl.workspace_id,'contractor_id',cpl.contractor_id,
      'company_name',c.company_name,'contact_name',c.contact_name))
      from public.contractor_portal_links cpl join public.contractors c on c.id=cpl.contractor_id
      where cpl.user_id=auth.uid() and cpl.revoked_at is null),'[]'::jsonb),
    'assignments',coalesce((select jsonb_agg(jsonb_build_object(
      'id',ja.id,'workspace_id',ja.workspace_id,'contractor_id',ja.contractor_id,'status',ja.status,'created_at',ja.created_at,
      'job',jsonb_build_object('id',j.id,'name',j.name,'status',j.status,
        'customer',case when ja.status='accepted' then jsonb_build_object('name',l.full_name,'phone',l.phone,'email',l.email) else null end),
      'appointments',(select coalesce(jsonb_agg(jsonb_build_object('id',a.id,'appointment_date',a.appointment_date,'appointment_end_at',to_jsonb(a)->'appointment_end_at','status',a.status)
        order by a.appointment_date),'[]'::jsonb) from public.appointments a where a.job_id=ja.job_id and a.contractor_id=ja.contractor_id)
    ) order by ja.created_at desc)
      from public.job_assignments ja join public.crm_jobs j on j.id=ja.job_id left join public.leads l on l.id=j.lead_id
      where exists(select 1 from public.contractor_portal_links cpl where cpl.user_id=auth.uid()
        and cpl.workspace_id=ja.workspace_id and cpl.contractor_id=ja.contractor_id and cpl.revoked_at is null)),'[]'::jsonb)
  );
$$;

create or replace function public.contractor_decide_assignment(p_assignment_id uuid,p_decision text)
returns text language plpgsql security definer set search_path = '' as $$
declare v_assignment public.job_assignments%rowtype; v_link_id uuid;
begin
  if lower(p_decision) not in ('accepted','rejected') then raise exception 'Invalid assignment decision.' using errcode='22023'; end if;
  select ja.* into v_assignment from public.job_assignments ja where ja.id=p_assignment_id for update;
  if not found then raise exception 'Assignment not found.' using errcode='P0002'; end if;
  select cpl.id into v_link_id from public.contractor_portal_links cpl
    where cpl.user_id=auth.uid() and cpl.workspace_id=v_assignment.workspace_id
      and cpl.contractor_id=v_assignment.contractor_id and cpl.revoked_at is null;
  if v_link_id is null then raise exception 'Assignment is not authorized for this contractor account.' using errcode='42501'; end if;
  if v_assignment.status <> 'offered' then raise exception 'Only an offered assignment can be accepted or rejected.' using errcode='22023'; end if;
  update public.job_assignments set status=lower(p_decision) where id=p_assignment_id;
  insert into public.portal_access_events(workspace_id,actor_user_id,portal_role,action,entity_type,entity_id,details)
  values(v_assignment.workspace_id,auth.uid(),'contractor','assignment_'||lower(p_decision),'job_assignment',p_assignment_id::text,
    jsonb_build_object('contractor_link_id',v_link_id,'contractor_id',v_assignment.contractor_id));
  return lower(p_decision);
end; $$;

revoke all on function public.create_portal_invitation(uuid,text,text,text,integer) from public,anon,authenticated;
revoke all on function public.revoke_portal_invitation(uuid) from public,anon;
revoke all on function public.accept_portal_invitation(text) from public,anon;
revoke all on function public.get_homeowner_portal_data() from public,anon;
revoke all on function public.homeowner_decide_estimate(uuid,text) from public,anon;
revoke all on function public.get_contractor_portal_data() from public,anon;
revoke all on function public.contractor_decide_assignment(uuid,text) from public,anon;
grant execute on function public.create_portal_invitation(uuid,text,text,text,integer) to service_role;
grant execute on function public.revoke_portal_invitation(uuid) to authenticated,service_role;
grant execute on function public.accept_portal_invitation(text) to authenticated,service_role;
grant execute on function public.get_homeowner_portal_data() to authenticated,service_role;
grant execute on function public.homeowner_decide_estimate(uuid,text) to authenticated,service_role;
grant execute on function public.get_contractor_portal_data() to authenticated,service_role;
grant execute on function public.contractor_decide_assignment(uuid,text) to authenticated,service_role;
