-- Production's historical default privileges grant SELECT, REFERENCES,
-- TRIGGER, and TRUNCATE on newly created public tables to API roles. The
-- launch migrations intentionally expose narrower interfaces, so normalize
-- effective privileges after the complete release chain is present.

revoke truncate, references, trigger on table
  public.plans,
  public.subscriptions,
  public.workspace_plan_status,
  public.job_assignments,
  public.appointments,
  public.communication_consents,
  public.communication_suppressions,
  public.communication_dnc_screenings,
  public.communication_provider_connections,
  public.communication_compliance_checks,
  public.stripe_webhook_events,
  public.billing_enrollment_consents,
  public.billing_notice_events,
  public.portal_invitations,
  public.homeowner_portal_links,
  public.contractor_portal_links,
  public.portal_access_events,
  public.ai_capability_registry,
  public.ai_agent_runs,
  public.ai_agent_action_audit,
  public.ai_agent_handoffs,
  public.ai_owner_attention_items,
  public.conversations,
  public.conversation_participants,
  public.messages,
  public.communication_transmissions,
  public.communication_provider_events,
  public.voice_notes,
  public.documents,
  public.document_events,
  public.calendar_event_mappings,
  public.crm_import_batches,
  public.notifications,
  public.business_phone_numbers,
  public.call_sessions
from anon, authenticated;

revoke select on table
  public.subscriptions,
  public.workspace_plan_status,
  public.job_assignments,
  public.appointments,
  public.communication_consents,
  public.communication_suppressions,
  public.communication_dnc_screenings,
  public.communication_provider_connections,
  public.communication_compliance_checks,
  public.stripe_webhook_events,
  public.billing_enrollment_consents,
  public.billing_notice_events,
  public.portal_invitations,
  public.homeowner_portal_links,
  public.contractor_portal_links,
  public.portal_access_events,
  public.ai_capability_registry,
  public.ai_agent_runs,
  public.ai_agent_action_audit,
  public.ai_agent_handoffs,
  public.ai_owner_attention_items,
  public.conversations,
  public.conversation_participants,
  public.messages,
  public.communication_transmissions,
  public.communication_provider_events,
  public.voice_notes,
  public.documents,
  public.document_events,
  public.calendar_event_mappings,
  public.crm_import_batches,
  public.notifications,
  public.business_phone_numbers,
  public.call_sessions
from anon;

-- Preserve the explicit authenticated interfaces defined by their owning
-- migrations. Direct mutations stay unavailable except for the documented
-- narrow column grants and lifecycle operations.
grant select on table
  public.subscriptions,
  public.workspace_plan_status,
  public.job_assignments,
  public.appointments,
  public.communication_consents,
  public.communication_suppressions,
  public.communication_dnc_screenings,
  public.communication_provider_connections,
  public.communication_compliance_checks,
  public.billing_enrollment_consents,
  public.billing_notice_events,
  public.portal_invitations,
  public.homeowner_portal_links,
  public.contractor_portal_links,
  public.portal_access_events,
  public.ai_capability_registry,
  public.ai_agent_runs,
  public.ai_agent_action_audit,
  public.ai_agent_handoffs,
  public.ai_owner_attention_items,
  public.conversations,
  public.conversation_participants,
  public.messages,
  public.communication_transmissions,
  public.communication_provider_events,
  public.voice_notes,
  public.documents,
  public.document_events,
  public.calendar_event_mappings,
  public.crm_import_batches,
  public.notifications,
  public.business_phone_numbers,
  public.call_sessions
to authenticated;

revoke all on table public.stripe_webhook_events from anon, authenticated;
