create table if not exists public.analytics_site_sources (
  hostname text primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  created_at timestamptz not null default now(),
  check (hostname = lower(hostname) and length(hostname) between 3 and 255)
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  workspace_id uuid references public.workspaces(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  session_id uuid not null,
  event_name text not null,
  path text not null,
  hostname text,
  referrer_host text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  check (event_name ~ '^[a-z][a-z0-9_]{1,63}$'),
  check (length(path) between 1 and 500),
  check (hostname is null or length(hostname) <= 255),
  check (referrer_host is null or length(referrer_host) <= 255),
  check (jsonb_typeof(metadata) = 'object'),
  check (pg_column_size(metadata) <= 4096)
);

alter table public.analytics_site_sources enable row level security;
alter table public.analytics_events enable row level security;
revoke all on public.analytics_site_sources from anon, authenticated;
revoke all on public.analytics_events from anon, authenticated;
grant all on public.analytics_site_sources to service_role;
grant all on public.analytics_events to service_role;

create index if not exists analytics_events_workspace_created_idx on public.analytics_events(workspace_id, created_at desc);
create index if not exists analytics_events_session_created_idx on public.analytics_events(session_id, created_at desc);
create index if not exists analytics_events_event_created_idx on public.analytics_events(event_name, created_at desc);
create index if not exists analytics_events_path_created_idx on public.analytics_events(path, created_at desc);

insert into public.analytics_site_sources(hostname, workspace_id)
select 'app.homeleadconnect.org', bp.workspace_id from public.business_profile bp
where lower(coalesce(bp.business_name,'')) like 'homelead connect%'
order by bp.created_at asc limit 1
on conflict (hostname) do update set workspace_id=excluded.workspace_id;

insert into public.analytics_site_sources(hostname, workspace_id)
select 'glittery-pavlova-0f33bd.netlify.app', bp.workspace_id from public.business_profile bp
where lower(coalesce(bp.business_name,'')) like 'homelead connect%'
order by bp.created_at asc limit 1
on conflict (hostname) do update set workspace_id=excluded.workspace_id;

create or replace function public.record_hlc_analytics_event(
  p_session_id uuid, p_event_name text, p_path text, p_hostname text default null,
  p_referrer_host text default null, p_metadata jsonb default '{}'::jsonb
) returns bigint language plpgsql security definer set search_path=pg_catalog,public as $$
declare
  v_user uuid:=auth.uid(); v_workspace uuid; v_id bigint;
  v_hostname text:=lower(nullif(btrim(p_hostname),''));
begin
  if p_session_id is null then raise exception 'session id required'; end if;
  if p_event_name is null or p_event_name !~ '^[a-z][a-z0-9_]{1,63}$' then raise exception 'invalid analytics event'; end if;
  if p_path is null or left(p_path,1)<>'/' or length(p_path)>500 then raise exception 'invalid analytics path'; end if;
  if p_metadata is null or jsonb_typeof(p_metadata)<>'object' or pg_column_size(p_metadata)>4096 then raise exception 'invalid analytics metadata'; end if;
  if v_user is not null then
    select p.workspace_id into v_workspace from public.profiles p where p.user_id=v_user and p.workspace_id is not null limit 1;
    if v_workspace is null then select wm.workspace_id into v_workspace from public.workspace_members wm where wm.user_id=v_user order by wm.created_at asc limit 1; end if;
  end if;
  if v_workspace is null and v_hostname is not null then select s.workspace_id into v_workspace from public.analytics_site_sources s where s.hostname=v_hostname; end if;
  if exists(select 1 from public.analytics_events e where e.session_id=p_session_id and e.event_name=p_event_name and e.path=p_path and e.created_at>now()-interval '2 seconds') then return null; end if;
  insert into public.analytics_events(workspace_id,user_id,session_id,event_name,path,hostname,referrer_host,metadata)
  values(v_workspace,v_user,p_session_id,p_event_name,p_path,v_hostname,left(nullif(btrim(p_referrer_host),''),255),p_metadata)
  returning id into v_id;
  return v_id;
end;
$$;
revoke all on function public.record_hlc_analytics_event(uuid,text,text,text,text,jsonb) from public;
grant execute on function public.record_hlc_analytics_event(uuid,text,text,text,text,jsonb) to anon,authenticated;

create or replace function public.get_hlc_analytics_summary(p_days integer default 30)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare
  v_user uuid:=auth.uid(); v_workspace uuid; v_days integer:=greatest(1,least(coalesce(p_days,30),365));
  v_since timestamptz; v_result jsonb;
begin
  if v_user is null then raise exception 'authentication required' using errcode='42501'; end if;
  select p.workspace_id into v_workspace from public.profiles p where p.user_id=v_user and p.workspace_id is not null limit 1;
  if v_workspace is null then select wm.workspace_id into v_workspace from public.workspace_members wm where wm.user_id=v_user order by wm.created_at asc limit 1; end if;
  if v_workspace is null or not exists(select 1 from public.workspace_members wm where wm.workspace_id=v_workspace and wm.user_id=v_user) then raise exception 'workspace access denied' using errcode='42501'; end if;
  v_since:=now()-make_interval(days=>v_days);
  select jsonb_build_object(
    'days',v_days,
    'page_views',count(*) filter(where event_name='page_view'),
    'sessions',count(distinct session_id),
    'authenticated_sessions',count(distinct session_id) filter(where user_id is not null),
    'visitor_sessions',count(distinct session_id) filter(where user_id is null),
    'leadscope_views',count(*) filter(where path='/estimator' and event_name='page_view'),
    'material_store_clicks',count(*) filter(where event_name='material_store_open'),
    'sign_in_starts',count(*) filter(where event_name='sign_in_started'),
    'service_request_starts',count(*) filter(where event_name='service_request_started'),
    'top_paths',coalesce((select jsonb_agg(jsonb_build_object('path',x.path,'views',x.views) order by x.views desc) from (select e.path,count(*)::bigint views from public.analytics_events e where e.workspace_id=v_workspace and e.created_at>=v_since and e.event_name='page_view' group by e.path order by views desc limit 8)x),'[]'::jsonb),
    'events',coalesce((select jsonb_agg(jsonb_build_object('event',x.event_name,'count',x.total) order by x.total desc) from (select e.event_name,count(*)::bigint total from public.analytics_events e where e.workspace_id=v_workspace and e.created_at>=v_since group by e.event_name order by total desc limit 12)x),'[]'::jsonb)
  ) into v_result from public.analytics_events e where e.workspace_id=v_workspace and e.created_at>=v_since;
  return coalesce(v_result,'{}'::jsonb);
end;
$$;
revoke all on function public.get_hlc_analytics_summary(integer) from public;
grant execute on function public.get_hlc_analytics_summary(integer) to authenticated;
